# 根目录 - 在这里定义要搜索的根路径
root_directory: "C:\\workspace"

# 指定过滤的作者
author: "GoldenZqqq"

# 输出文件存放的目录（默认是桌面）
output_directory: "~/Desktop"

# 开始时间，可选，默认今天 2024-10-14
start_date: ""

# 结束时间，可选，默认今天 2024-10-14
end_date: ""

# 是否输出详细日志，可选，默认 true
detailed_output: true

# 是否在最后的总结日志输出中列出每行的项目名与分支名，默认 true
show_project_and_branch: true

# 自定义项目名称
project_names:
