# 根目录 - 在这里定义要搜索的根路径
root_directory: "C:\\workspace"

# 指定过滤的作者
author: "GoldenZqqq"

# 输出文件存放的目录（默认是桌面）
output_directory: "~/Desktop"

# 开始时间，可选，默认今天 2024-10-14
start_date: ""

# 结束时间，可选，默认今天 2024-10-14
end_date: ""

# 是否输出详细日志，可选，默认 true
detailed_output: true

# 是否在最后的总结日志输出中列出每行的项目名与分支名，默认 true
show_project_and_branch: true

# 是否在提取日志之前拉取最新代码，默认 false
pull_latest_code: false

# 是否提取所有分支的提交记录，默认 false 只提取当前分支，建议保持不变 
# TODO: 考虑切换分支前如果本地有未提交的代码，stash or force
extract_all_branches: false

# 自定义项目名称，格式为：项目名(分支名): "项目名称-"    
# ep: ruoyi-vue-admin(master): "若依后台管理系统-"
#     ruoyi-mall-h5(master): "若依商城用户端H5-"
project_names:
